version: "3.7"

services:
  bikeshop-api:
    build: ./src/BikeShop.API
    container_name: bikeshop-api
    restart: unless-stopped
    ports:
      - 5002:80
    networks:
      - bikeshop

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - bikeshop
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    driver: local