version: "3.8"

services:
  bikeshop-api:
    build: ./src/BikeShop.API
    container_name: bikeshop-api
    restart: unless-stopped
    ports:
      - 5002:80
    networks:
      - bikeshop

  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - bikeshop
    volumes:
      - postgres:/var/lib/postgresql/data
  #      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql


  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - bikeshop
    volumes:
      - mongo:/data/db

volumes:
  postgres:
    driver: local
  mongo:
    driver: local

networks:
  bikeshop:
    name: bikeshop
